version: '3'

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../frontend/public:/usr/share/nginx/html/frontend
      - ../backend/public:/usr/share/nginx/html/backend
      - ../var/log:/var/log
      - ./nginx/root_home:/root
    ports:
      - "80:80"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      backend:
        aliases:
          - fullstackexercise.frontend
          - fullstackexercise.backend

  php-fpm:
    build:
      context: ../backend
      dockerfile: ../docker/php-fpm/Dockerfile
    environment:
      - DATABASE_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - ../backend/config:/usr/share/fullstackExercise/config
      - ../backend/public:/usr/share/fullstackExercise/public
      - ../backend/src:/usr/share/fullstackExercise/src
      - ../backend/tests:/usr/share/fullstackExercise/tests
      - ../backend/spec:/usr/share/fullstackExercise/spec
      - ../backend/.env:/usr/share/fullstackExercise/.env
      - ../backend/.env.test:/usr/share/fullstackExercise/.env.test
      - ../backend/.gitignore:/usr/share/fullstackExercise/.gitignore
      - ../backend/composer.json:/usr/share/fullstackExercise/composer.json
      - ../backend/composer.lock:/usr/share/fullstackExercise/composer.lock
      - ../backend/kahlan-config.php:/usr/share/fullstackExercise/kahlan-config.php
      - ../backend/phpcs.xml.dist:/usr/share/fullstackExercise/phpcs.xml.dist
      - ../backend/phpmd.xml:/usr/share/fullstackExercise/phpmd.xml
      - ../backend/phpunit.xml.dist:/usr/share/fullstackExercise/phpunit.xml.dist
      - ../backend/symfony.lock:/usr/share/fullstackExercise/symfony.lock
      - ./php-fpm/root_home:/root
    stdin_open: true
    tty: true
    networks:
      - backend

  mariadb:
    build:
      context: ./mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ../var/lib/mysql:/var/lib/mysql
      - ./mariadb/root_home:/root
    stdin_open: true
    tty: true
    networks:
      backend:
        aliases:
          - database.backend
  node:
    build:
      context: ../frontend
      dockerfile: ../docker/node/Dockerfile
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
    volumes:
      - ../frontend/public:/usr/share/fullstackExercise/public
      - ../frontend/src:/usr/share/fullstackExercise/src
      - ../frontend/test:/usr/share/fullstackExercise/test
      - ../frontend/package.json:/usr/share/fullstackExercise/package.json
      - ../frontend/package-lock.json:/usr/share/fullstackExercise/package-lock.json
      - ../frontend/vue.config.js:/usr/share/fullstackExercise/vue.config.js
      - ../frontend/babel.config.js:/usr/share/fullstackExercise/babel.config.js
      - ./node/root_home:/root
    stdin_open: true
    tty: true
    networks:
      backend:
        aliases:
          - vuejs.backend

networks:
  backend:
    driver: "bridge"
