version: '3'

services:
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../frontend/public:/usr/share/nginx/html/frontend
      - ../backend/public:/usr/share/nginx/html/backend
      - ../var/log:/var/log
      - ./nginx/root_home:/root
    ports:
      - "80:80"
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      backend:
        aliases:
          - fullstackexercise.frontend
          - fullstackexercise.backend

  php-fpm:
    build:
      context: ./php-fpm
    environment:
      - DATABASE_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    volumes:
      - ../backend/config:/usr/share/fullstackExercise/config
      - ../backend/public:/usr/share/fullstackExercise/public
      - ../backend/src:/usr/share/fullstackExercise/src
      - ../backend/tests:/usr/share/fullstackExercise/tests
      - ../backend/spec:/usr/share/fullstackExercise/spec
      - ./php-fpm/app_root/composer.json:/usr/share/fullstackExercise/composer.json
      - ./php-fpm/app_root/composer.lock:/usr/share/fullstackExercise/composer.lock
      - ./php-fpm/app_root/kahlan-config.php:/usr/share/fullstackExercise/kahlan-config.php
      - ./php-fpm/root_home:/root
    stdin_open: true
    tty: true
    networks:
      - backend

  mariadb:
    build:
      context: ./mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - ../var/lib/mysql:/var/lib/mysql
      - ./mariadb/root_home:/root
    stdin_open: true
    tty: true
    networks:
      backend:
        aliases:
          - database.backend
  node:
    build:
      context: ./node
    environment:
      - GITHUB_PERSONAL_ACCESS_TOKEN=${GITHUB_PERSONAL_ACCESS_TOKEN}
    volumes:
      - ../frontend/public:/usr/share/fullstackExercise/public
      - ../frontend/src:/usr/share/fullstackExercise/src
      - ../frontend/test:/usr/share/fullstackExercise/test
      - ./node/root_home:/root
      - ./node/config/package.json:/usr/share/fullstackExercise/package.json
      - ./node/config/package-lock.json:/usr/share/fullstackExercise/package-lock.json
      - ./node/config/vue.config.js:/usr/share/fullstackExercise/vue.config.js
      - ./node/config/babel.config.js:/usr/share/fullstackExercise/babel.config.js
    stdin_open: true
    tty: true
    networks:
      backend:
        aliases:
          - vuejs.backend

networks:
  backend:
    driver: "bridge"
