FROM node
RUN apt-get update
RUN apt-get install libnss3-dev libatk-bridge2.0-0 libx11-xcb1 libdrm-dev libxkbcommon-dev libgtk-3-0 libasound2 --yes
WORKDIR  /usr/share/fullstackExercise/
RUN npm install
